const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require('playwright');
if(process.env.CSI_BACKEND && process.env.CSI_BACKEND!=='local')throw Error('Pilot walkthrough is LOCAL only');
const {config,service,ok,login:apiLogin}=require('../backend/local.cjs');
const f=JSON.parse(fs.readFileSync('.local/fixture.json')),base='http://127.0.0.1:3100';let browser,admin;
before(async()=>{assert.equal(config.API_URL,'http://127.0.0.1:55421');browser=await chromium.launch();admin=await apiLogin('admin');fs.mkdirSync('.local/pilot',{recursive:true});});
after(async()=>{await browser?.close();await admin?.auth.signOut({scope:'local'});});
async function open(t,role){const context=await browser.newContext({viewport:{width:390,height:844}}),p=await context.newPage(),errors=[];p.setDefaultTimeout(10000);
 await context.route('**/*',r=>[base,config.API_URL].includes(new URL(r.request().url()).origin)?r.continue():r.abort());p.on('pageerror',e=>errors.push(e.message));
 t.after(async()=>{await context.close();assert.deepEqual(errors,[]);});await p.goto(base);
 const html=await (await context.request.get(base)).text();const asset=html.match(/<script[^>]+src="([^"]+)"/)[1];assert((await(await context.request.get(base+asset)).text()).includes(config.API_URL));
 if(role)await signIn(p,role);return p;
}
async function signIn(p,role){await p.getByLabel('E-mail',{exact:true}).fill(f.accounts[role].email);await p.getByLabel('Wachtwoord',{exact:true}).fill(f.accounts[role].password);await p.getByLabel('Wachtwoord',{exact:true}).press('Enter');await p.getByRole('button',{name:'Uitloggen',exact:true}).waitFor();}
async function closeMessage(p){const close=p.getByRole('button',{name:'Melding sluiten',exact:true});if(await close.count())await close.last().click();}
const nav=(p,name)=>p.getByRole('navigation',{name});

test('pilot login: labelled fields, Enter submit and understandable error',async t=>{const p=await open(t);await p.getByLabel('E-mail',{exact:true}).fill(f.accounts.a.email);await p.getByLabel('Wachtwoord',{exact:true}).fill('wrong-password');await p.getByLabel('Wachtwoord',{exact:true}).press('Enter');await p.getByRole('alert').filter({hasText:'E-mailadres of wachtwoord klopt niet'}).waitFor();await closeMessage(p);await signIn(p,'a');await p.getByText('Team TEST - Groep A',{exact:true}).waitFor();});

test('pilot participant: keyboard card, note feedback, purchase and balance',async t=>{
 const clue=ok(await service.from('clues_base').insert({title:'PILOT - Aanwijzing '+Date.now(),description:'Fictieve pilotaanwijzing',price:2,is_visible:true,is_active:true}).select().single());t.after(()=>admin.from('clues').delete().eq('id',clue.id).then(ok));
 const p=await open(t,'a');await p.getByRole('button',{name:/Theorie-spoor/}).press('Enter');await p.locator('select').first().selectOption(f.suspect);await p.getByRole('button',{name:'Notitie toevoegen',exact:true}).click();
 const note='PILOT observatie '+Date.now();await p.getByLabel('Notitie over TEST - Verdachte',{exact:true}).fill(note);await p.getByRole('button',{name:'Notitie opslaan',exact:true}).click();const saved=p.getByRole('status').filter({hasText:'Notitie opgeslagen.'});await saved.waitFor();const box=await saved.boundingBox();assert(box.y>=0&&box.y+box.height<=844);await closeMessage(p);await p.getByText(note,{exact:true}).waitFor();
 await p.getByRole('button',{name:/^📄 Aanwijzingen$/}).click();const balance=ok(await service.from('groups').select('credits').eq('id',f.groupA).single()).credits;
 const card=p.getByRole('heading',{name:clue.title,exact:true}).locator('..').locator('..');await card.getByRole('button',{name:'Koop voor 2 pegels',exact:true}).click();await card.getByText('⏳ Wacht op vrijgave',{exact:true}).waitFor();assert.equal(ok(await service.from('groups').select('credits').eq('id',f.groupA).single()).credits,balance-2);await closeMessage(p);await p.getByRole('button',{name:/🏠 Home/}).click();await p.getByRole('button',{name:/💰 Pegels/}).click();await p.getByRole('heading',{name:'Pegels geschiedenis'}).waitFor();
});

test('pilot participant: pending clue explains release without another purchase',async t=>{const p=await open(t,'b');await p.getByRole('button',{name:/^📄 Aanwijzingen$/}).click();const card=p.getByRole('heading',{name:'TEST - Afgeschermd bestand',exact:true}).locator('..').locator('..');await card.getByText('⏳ Wacht op vrijgave',{exact:true}).waitFor();assert.equal(await card.getByRole('button',{name:'Aanwijzing openen'}).count(),0);await card.getByText(/Je hoeft niets opnieuw te kopen/).waitFor();});

test('pilot suspect: own dossier and available research, no misleading other dossier',async t=>{const p=await open(t,'suspect');await p.getByText('Mijn verdachte-dossier',{exact:true}).waitFor();await p.getByText(/Je ziet alleen informatie die bij jouw eigen dossier beschikbaar is/).waitFor();assert.equal(await p.locator('select').count(),0);assert.equal(await p.getByText('TEST - Ander beveiligd dossier',{exact:true}).count(),0);await p.getByText('Bekijk verdachteprofiel',{exact:true}).click();await p.getByText('Uitsluitend fictieve testgegevens.',{exact:true}).waitFor();await p.screenshot({path:'.local/pilot/suspect.png'});});

test('pilot jury: one-click dossier, release feedback, explicit correction and overview',async t=>{const p=await open(t,'jury');assert.equal(await p.getByRole('button',{name:/Beheer|backup|Reset/}).count(),0);await nav(p,'Jurynavigatie').getByRole('button',{name:'Dossiers',exact:true}).click();await p.getByLabel('Verhoordossier',{exact:true}).selectOption(f.suspect);assert.equal(await p.locator('#jury-dossiers').getByRole('heading',{name:'TEST - Verdachte',exact:true}).count(),1);
 await nav(p,'Jurynavigatie').getByRole('button',{name:'Vrijgeven',exact:true}).click();const release=p.locator('#jury-vrijgave').getByRole('button',{name:'Vrijgeven',exact:true}).first();await release.click();await p.getByRole('status').filter({hasText:'Aanwijzing vrijgegeven.'}).waitFor();await closeMessage(p);
 await nav(p,'Jurynavigatie').getByRole('button',{name:'Pegels',exact:true}).click();const start=ok(await service.from('groups').select('credits').eq('id',f.groupB).single()).credits;await p.getByLabel('Groep voor pegelcorrectie').selectOption(f.groupB);await p.getByLabel('Aantal pegels').fill('2');await p.getByLabel('Reden pegelcorrectie').fill('PILOT opdracht');await p.getByText(`TEST - Groep B: ${start} → ${start+2} pegels`,{exact:true}).waitFor();await p.getByRole('button',{name:'Pegels verwerken',exact:true}).click();await p.getByText('Pegels bijgewerkt.',{exact:true}).waitFor();assert.equal(ok(await service.from('groups').select('credits').eq('id',f.groupB).single()).credits,start+2);await closeMessage(p);await nav(p,'Jurynavigatie').getByRole('button',{name:'Overzicht',exact:true}).click();assert((await p.getByRole('heading',{name:'Juryoverzicht'}).boundingBox()).y<100);
});

test('pilot admin: cards, group monitoring, accounts, backup health and all navigation',async t=>{const p=await open(t,'admin');await p.getByRole('button',{name:/👥 Actieve groepen/}).press(' ');await nav(p,'Beheernavigatie').getByRole('button',{name:/Beheer/}).click();await p.getByRole('heading',{name:'Rollen en toegang'}).waitFor();await nav(p,'Beheernavigatie').getByRole('button',{name:/Controle/}).click();await p.getByRole('heading',{name:'Systeem / Backupstatus'}).waitFor();await p.getByRole('status').filter({hasText:'TEST: nachtbackup overgeslagen'}).waitFor();for(const label of ['Groepen','Aanwijzingen','Spelerbeeld','Pegels','Verhoor','Dashboard'])await nav(p,'Beheernavigatie').getByRole('button',{name:new RegExp(label)}).click();await p.getByRole('heading',{name:'Spel in één oogopslag'}).waitFor();});

for(const role of [null,'a','jury','admin'])test(`pilot compact responsive: ${role||'login'}`,async t=>{const p=await open(t,role);for(const [width,height]of [[390,844],[360,800],[1280,900],[844,390]]){await p.setViewportSize({width,height});const geometry=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,nav:[...document.querySelectorAll('nav button')].map(b=>({width:b.getBoundingClientRect().width,height:b.getBoundingClientRect().height,overflow:b.scrollWidth>b.clientWidth}))}));assert.equal(geometry.overflow,false);for(const b of geometry.nav){assert(b.width>=80);assert(b.height>=44);assert.equal(b.overflow,false);}if(width===390)await p.screenshot({path:`.local/pilot/${role||'login'}.png`});}});
