const fs=require('fs'),assert=require('assert/strict');const c=JSON.parse(fs.readFileSync('.local/hosted-backend.json'));require('./safety.cjs').validate(c,{target:'hosted',allowHosted:process.argv.includes('--allow-hosted')});
const count=Number(process.argv.find(a=>a.startsWith('--samples='))?.split('=')[1]||1);assert(Number.isInteger(count)&&count>=1&&count<=60);
const output=process.argv.find(a=>a.startsWith('--out='))?.slice(6)||'server-metrics';assert(/^[a-z0-9-]+$/.test(output));
(async()=>{let previous;for(let i=0;i<count;i++){
const r=await fetch(c.API_URL+'/customer/v1/privileged/metrics',{headers:{authorization:'Basic '+Buffer.from('service_role:'+c.SERVICE_ROLE_KEY).toString('base64')},redirect:'error',signal:AbortSignal.timeout(15000)});assert.equal(r.status,200);const txt=await r.text();const at=new Date().toISOString();fs.writeFileSync('.local/performance/prom-'+at.replace(/[:.]/g,'-')+'.txt',txt);
const lines=txt.split('\n').filter(s=>s&&!s.startsWith('#'));const sum=name=>lines.filter(s=>s.startsWith(name+' ')||s.startsWith(name+'{')).reduce((n,s)=>n+Number(s.slice(s.lastIndexOf(' ')+1)),0);
const cpu=lines.filter(s=>s.startsWith('node_cpu_seconds_total{'));const total=cpu.reduce((n,s)=>n+Number(s.slice(s.lastIndexOf(' ')+1)),0),idle=cpu.filter(s=>s.includes('mode="idle"')).reduce((n,s)=>n+Number(s.slice(s.lastIndexOf(' ')+1)),0);
const m={at,cpuBusyPercent:previous?100*(1-(idle-previous.idle)/(total-previous.total)):null,memoryAvailableBytes:sum('node_memory_MemAvailable_bytes'),memoryTotalBytes:sum('node_memory_MemTotal_bytes'),load1:sum('node_load1'),poolWaiting:sum('pgbouncer_pools_client_waiting_connections'),poolMaxWait:sum('pgbouncer_pools_client_maxwait_seconds'),restPoolWaiting:sum('pgrst_db_pool_waiting'),restPoolTimeouts:sum('pgrst_db_pool_timeouts_total'),subscriptions:sum('realtime_postgres_changes_client_subscriptions'),replicationLagBytes:sum('replication_realtime_lag_bytes')};previous={idle,total};fs.appendFileSync('.local/performance/'+output+'.jsonl',JSON.stringify(m)+'\n');console.log(JSON.stringify(m));if(i+1<count)await new Promise(r=>setTimeout(r,60000));
}})().catch(e=>{console.error(e.message);process.exitCode=1});
