// Publish only derived measurements; raw request fingerprints and credentials stay local.
const fs=require('node:fs'),assert=require('node:assert/strict');
const read=name=>JSON.parse(fs.readFileSync('.local/performance/'+name+'.json','utf8'));
const round=n=>n==null?null:Math.round(n*100)/100;
function profile(name){const r=read(name);return {network:r.network,viewport:r.viewport,roles:r.roles.map(x=>{
 const backend=x.requests.filter(q=>q.backend),idle=backend.filter(q=>q.phase==='idle');
 return {role:x.role,usableMs:x.usableMs,backendRequests:backend.length,initialRequests:backend.filter(q=>q.phase==='initial').length,navigationRequests:backend.filter(q=>q.phase==='navigation').length,idleRequests:idle.length,idleMs:x.idleMs,idleBytes:idle.reduce((n,q)=>n+q.bytes,0),backendBytes:backend.reduce((n,q)=>n+q.bytes,0),identicalRequestsWithin1500ms:x.identicalRequestsWithin1500ms??null,navigation:x.navigation,reactCommits:x.profile.commits,domNodes:x.profile.domNodes,longTasks:x.profile.longTasks.map(round),taskMs:round(x.metrics.TaskDuration*1000),scriptMs:round(x.metrics.ScriptDuration*1000),heapBytes:x.metrics.JSHeapUsedSize,resourceTransferBytes:x.profile.resources.reduce((n,r)=>n+r.transfer,0),sockets:x.sockets,errors:x.errors};
 })};}
const load=read('load-local-final-A-10');assert(load.passed);assert.equal(load.errors.length,0);
const plans=read('query-plans');
const data={date:'2026-09-29',baselineCommit:'8ef8bee',environment:'loopback Chromium 390x844; uncompressed static assets; Node 24.21.0; no hosted load',baseline:profile('baseline-normal'),matchedBefore:profile('matched-before-normal'),matchedAfter:profile('matched-after-normal'),mobile4g:profile('final-4g'),slowBefore:profile('baseline-slow'),slowAfterIntermediate:profile('after-slow'),slowAfterFinal:profile('final-slow'),slowCaveat:'Baseline admin did not become usable; new slow run predates the final subscription-gap correction. Final participant/admin rerun after targeted timeout and photo URL fixes; other roles measured in the earlier full slow run.',large:read('large-after-render'),render:read('large-render-comparison'),clueLists:{before:read('large-clues-before'),after:read('large-current')},bundle:read('bundle'),builtAssets:read('bundle-built'),plans:Object.fromEntries(Object.entries(plans).map(([k,v])=>[k,{executionMs:v[0]['Execution Time'],planningMs:v[0]['Planning Time']}])) ,localLoad:{options:load.options,scope:load.scope,passed:load.passed,durationSeconds:load.durationSeconds,loadDurationSeconds:load.loadDurationSeconds,summary:load.summary,minuteWindows:load.minuteWindows,channelSampleCount:load.channelCounts?.length,maximumChannelsPerClient:load.channelCounts?.length?Math.max(...load.channelCounts.map(c=>c.channels)):null,roles:Object.fromEntries(['a','b','suspect','jury','admin'].map(role=>{const s=load.samples.filter(s=>s.role===role&&s.kind==='request');return [role,{requests:s.length,errors:s.filter(s=>!s.ok).length}];}))},tests:{executions:214,duplicatePrivacyExecutions:4,unique:210}};
assert.equal(data.matchedBefore.roles.length,6);assert.equal(data.matchedAfter.roles.length,6);
assert(data.matchedAfter.roles.every(r=>r.errors.length===0));
assert.equal(data.slowAfterFinal.roles.length,2);assert(data.slowAfterFinal.roles.every(r=>r.errors.length===0));
for(const chunk of data.bundle)for(const module of chunk.modules)if(/^(?:[A-Za-z]:\/|\/)/.test(module.module))module.module=module.module.split('/').at(-1);
fs.mkdirSync('docs/performance',{recursive:true});fs.writeFileSync('docs/performance/measurements.json',JSON.stringify(data,null,2)+'\n');
const lines=['| Rol | Bruikbaar vóór → na (ms) | Backendrequests vóór → na | Idle requests vóór → na (22 s) | Idle responsebytes vóór → na |','|---|---:|---:|---:|---:|'];
for(const before of data.matchedBefore.roles){const after=data.matchedAfter.roles.find(r=>r.role===before.role);lines.push(`| ${before.role} | ${before.usableMs} → ${after.usableMs} | ${before.backendRequests} → ${after.backendRequests} | ${before.idleRequests} → ${after.idleRequests} | ${before.idleBytes} → ${after.idleBytes} |`);}
lines.push('','Landing/login gebruiken 1 s idle. Backendrequests omvatten auth/REST/Storage; bytes zijn gedecodeerde responsebytes, geen gemeten internet-egress. Volledige snapshots vóór optimalisatie kunnen afgekapt zijn; na optimalisatie worden alle pagina’s geladen. Dit verklaart een deel van extra initial requests.','',`Lokale tien-sessiesrun: ${round(load.loadDurationSeconds)} s workload, ${round(load.durationSeconds)} s inclusief setup/cleanup; ${load.summary.request.count} requests, ${round(load.summary.request.perSecond)}/s over de hele run; fouten 0. Snapshot p50/p95/p99 **${round(load.summary.snapshot.p50)}/${round(load.summary.snapshot.p95)}/${round(load.summary.snapshot.p99)} ms**, request p95 **${round(load.summary.request.p95)} ms**, ${load.summary['realtime-join'].count} joins inclusief reconnect. Dit is lokale API-/Realtime-validatie, geen hosted capaciteitsgrens.`);
const file='docs/PERFORMANCE-SCALE-REPORT.md',report=fs.readFileSync(file,'utf8');fs.writeFileSync(file,report.replace(/<!-- MEASUREMENTS START -->[\s\S]*?<!-- MEASUREMENTS END -->/,'<!-- MEASUREMENTS START -->\n'+lines.join('\n')+'\n<!-- MEASUREMENTS END -->'));
console.log('Sanitized measurements and comparison table written; raw data remains ignored.');
