export const styles = {
  app: {
    fontFamily: "Arial, sans-serif",
    background: "#0f0f10",
    minHeight: "var(--app-viewport-height, 100vh)",
    boxSizing: "border-box",
    padding: "calc(14px + env(safe-area-inset-top, 0px)) calc(14px + env(safe-area-inset-right, 0px)) calc(90px + env(safe-area-inset-bottom, 0px)) calc(14px + env(safe-area-inset-left, 0px))",
    color: "#f4f4f5",
  },
  shell: {
    maxWidth: 1280,
    margin: "0 auto",
  },
  card: {
    background: "#18181b",
    border: "1px solid #3f3f46",
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit,minmax(min(300px,100%),1fr))",
    gap: 14,
  },
  input: {
    width: "100%",
    padding: 11,
    marginBottom: 10,
    borderRadius: 12,
    border: "1px solid #52525b",
    background: "#09090b",
    color: "#f4f4f5",
    boxSizing: "border-box",
    fontSize: 16,
  },
  select: {
    width: "100%",
    padding: 11,
    marginBottom: 10,
    borderRadius: 12,
    border: "1px solid #52525b",
    background: "#09090b",
    color: "#f4f4f5",
    boxSizing: "border-box",
    fontSize: 16,
  },
  textarea: {
    width: "100%",
    padding: 11,
    marginBottom: 10,
    borderRadius: 12,
    border: "1px solid #52525b",
    background: "#09090b",
    color: "#f4f4f5",
    minHeight: 90,
    boxSizing: "border-box",
    fontSize: 16,
  },
  button: {
    padding: "11px 14px",
    borderRadius: 12,
    border: "1px solid #52525b",
    background: "#991b1b",
    color: "#fff",
    fontWeight: 700,
    cursor: "pointer",
    marginRight: 8,
    marginBottom: 8,
    fontSize: 15,
  },
  buttonSecondary: {
    padding: "11px 14px",
    borderRadius: 12,
    border: "1px solid #52525b",
    background: "#27272a",
    color: "#fff",
    fontWeight: 700,
    cursor: "pointer",
    marginRight: 8,
    marginBottom: 8,
    fontSize: 15,
  },
  buttonDanger: {
    padding: "11px 14px",
    borderRadius: 12,
    border: "1px solid #7f1d1d",
    background: "#450a0a",
    color: "#fecaca",
    fontWeight: 700,
    cursor: "pointer",
    marginRight: 8,
    marginBottom: 8,
    fontSize: 15,
  },
  subtle: {
    color: "#a1a1aa",
    fontSize: 14,
  },
  badge: {
    display: "inline-block",
    padding: "5px 10px",
    borderRadius: 999,
    background: "#27272a",
    border: "1px solid #52525b",
    marginRight: 8,
    marginTop: 8,
    fontSize: 13,
  },
  img: {
    width: 120,
    height: 120,
    objectFit: "cover",
    borderRadius: 12,
    marginBottom: 10,
    border: "1px solid #52525b",
    cursor: "pointer",
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.82)",
    zIndex: 999,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "max(18px, env(safe-area-inset-top, 0px)) max(18px, env(safe-area-inset-right, 0px)) max(18px, env(safe-area-inset-bottom, 0px)) max(18px, env(safe-area-inset-left, 0px))",
  },
  modalCard: {
    maxWidth: 900,
    maxHeight: "100%",
    overflowY: "auto",
    width: "100%",
    background: "#18181b",
    border: "1px solid #52525b",
    borderRadius: 18,
    padding: 14,
    boxSizing: "border-box",
  },
  modalImage: {
    width: "100%",
    maxHeight: "78vh",
    objectFit: "contain",
    borderRadius: 14,
  },
  error: {
    color: "#fca5a5",
    marginTop: 10,
  },
  ok: {
    color: "#86efac",
    marginTop: 10,
  },
  header: {
    position: "sticky",
    top: "env(safe-area-inset-top, 0px)",
    zIndex: 20,
    background: "rgba(15,15,16,0.94)",
    backdropFilter: "blur(10px)",
    borderBottom: "1px solid #27272a",
    padding: "10px 0 12px",
    marginBottom: 14,
  },
  titleRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
  },
  mobileNav: {
    position: "fixed",
    left: 0,
    right: 0,
    bottom: 0,
    padding: "0 env(safe-area-inset-right, 0px) env(safe-area-inset-bottom, 0px) env(safe-area-inset-left, 0px)",
    zIndex: 50,
    background: "#18181b",
    borderTop: "1px solid #3f3f46",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(64px, 1fr))",
    gap: 0,
  },
  adminMobileNav: {
    position: "fixed",
    left: 0,
    right: 0,
    bottom: 0,
    padding: "0 env(safe-area-inset-right, 0px) env(safe-area-inset-bottom, 0px) env(safe-area-inset-left, 0px)",
    zIndex: 55,
    background: "#18181b",
    borderTop: "1px solid #3f3f46",
    display: "grid",
    gridTemplateColumns: "repeat(9,minmax(0,1fr))",
    gap: 0,
  },
  navButton: (active) => ({
    minWidth: 0,
    overflowWrap: "anywhere",
    padding: "10px clamp(2px, 0.5vw, 6px)",
    border: "none",
    borderRight: "1px solid #27272a",
    background: active ? "#991b1b" : "#18181b",
    color: "#f4f4f5",
    fontSize: 12,
    fontWeight: active ? 800 : 600,
    cursor: "pointer",
  }),
  statNumber: {
    fontSize: 28,
    fontWeight: 800,
    marginTop: 6,
  },
  link: {
    color: "#93c5fd",
    fontWeight: 700,
  },
};
